# Generated by Django 5.2.17 on 2026-10-10 17:44

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("startups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=12)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("description_text", models.TextField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("link", models.CharField(blank=True, max_length=300)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("registration_open", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                            ("removed", "Removed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("recording_url", models.CharField(blank=True, max_length=300)),
                ("summary", models.TextField(blank=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemoDaySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                ("pitch_link", models.CharField(blank=True, max_length=300)),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="startups.startup",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("reminded_24h_at", models.DateTimeField(blank=True, null=True)),
                ("reminded_1h_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status", "starts_at"], name="event_status_start_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["type", "starts_at"], name="event_type_start_idx"),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__in", ("demo_day", "workshop", "meetup", "announcement"))
                ),
                name="event_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("draft", "published", "cancelled", "removed"))),
                name="event_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="event_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="demodayslot",
            constraint=models.UniqueConstraint(
                fields=("event", "position"), name="slot_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="demodayslot",
            constraint=models.UniqueConstraint(
                fields=("event", "startup"), name="slot_startup_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["user", "-created_at"], name="event_reg_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="event_registration_unique"
            ),
        ),
    ]
