# Generated by Django 5.2.17 on 2026-10-10 09:01

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("startups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=12)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField()),
                ("body_text", models.TextField()),
                ("cover_key", models.CharField(blank=True, max_length=200)),
                ("external_url", models.CharField(blank=True, max_length=300)),
                ("comments_enabled", models.BooleanField(default=True)),
                ("public", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("removed", "Removed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("banner_starts_at", models.DateTimeField(blank=True, null=True)),
                ("banner_ends_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("reaction_count", models.PositiveIntegerField(default=0)),
                ("reaction_counts", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="editorial.editorialitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=12)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="editorial.editorialitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemStartup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="startup_links",
                        to="editorial.editorialitem",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="startups.startup",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="WinSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=12)),
                ("title", models.CharField(max_length=160)),
                ("evidence_url", models.CharField(max_length=300)),
                ("details", models.CharField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=500)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="editorial.editorialitem",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="startups.startup",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="win_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="editorialitem",
            index=models.Index(fields=["status", "-publish_at"], name="editorial_status_idx"),
        ),
        migrations.AddIndex(
            model_name="editorialitem",
            index=models.Index(fields=["-published_at", "-id"], name="editorial_published_idx"),
        ),
        migrations.AddIndex(
            model_name="editorialitem",
            index=models.Index(fields=["type", "-published_at"], name="editorial_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="editorialitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        ("award", "celebration", "partnership", "funding", "news", "announcement"),
                    )
                ),
                name="editorial_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="editorialitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("draft", "scheduled", "published", "removed"))),
                name="editorial_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="editorialitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("banner_starts_at__isnull", True),
                    ("banner_ends_at__isnull", True),
                    ("banner_ends_at__gt", models.F("banner_starts_at")),
                    _connector="OR",
                ),
                name="editorial_banner_window",
            ),
        ),
        migrations.AddIndex(
            model_name="itemcomment",
            index=models.Index(fields=["item", "created_at", "id"], name="editorial_comment_idx"),
        ),
        migrations.AddConstraint(
            model_name="itemreaction",
            constraint=models.UniqueConstraint(
                fields=("item", "user", "kind"), name="editorial_reaction_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemreaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("like", "celebrate", "insightful"))),
                name="editorial_reaction_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemstartup",
            constraint=models.UniqueConstraint(
                fields=("item", "startup"), name="editorial_startup_once"
            ),
        ),
        migrations.AddIndex(
            model_name="winsubmission",
            index=models.Index(fields=["status", "created_at"], name="win_queue_idx"),
        ),
        migrations.AddIndex(
            model_name="winsubmission",
            index=models.Index(fields=["submitter", "-created_at"], name="win_mine_idx"),
        ),
        migrations.AddConstraint(
            model_name="winsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("award", "funding", "partnership"))),
                name="win_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="winsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "approved", "rejected"])),
                name="win_status_valid",
            ),
        ),
    ]
