# Generated by Django 5.2.17 on 2026-10-09 19:55

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=120)),
                ("headline", models.CharField(blank=True, max_length=160)),
                ("bio", models.CharField(blank=True, max_length=500)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("custom_skills", models.JSONField(blank=True, default=list)),
                ("open_to", models.JSONField(blank=True, default=list)),
                ("linkedin_url", models.CharField(blank=True, max_length=300)),
                ("x_url", models.CharField(blank=True, max_length=300)),
                ("website_url", models.CharField(blank=True, max_length=300)),
                ("photo_key", models.CharField(blank=True, max_length=200)),
                ("visibility", models.JSONField(blank=True, default=dict)),
                ("completeness_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "skills",
                    models.ManyToManyField(blank=True, related_name="+", to="reference.skill"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founder_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["country"], name="profile_country_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("completeness_score__lte", 100)),
                        name="profile_score_max_100",
                    )
                ],
            },
        ),
    ]
