# Generated by Django 5.2.17 on 2026-10-09 19:55

import apps.core.ids
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("country", models.CharField(max_length=2)),
                ("city", models.CharField(max_length=100)),
                ("year_founded", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pitch", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("website_url", models.CharField(blank=True, max_length=300)),
                ("logo_key", models.CharField(blank=True, max_length=200)),
                ("directory_opt_in", models.BooleanField(default=False)),
                ("featured_at", models.DateTimeField(blank=True, null=True)),
                ("visibility", models.JSONField(blank=True, default=dict)),
                ("completeness_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_startups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.sector",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.stage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StartupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invited_email", models.EmailField(blank=True, max_length=254)),
                ("title", models.CharField(blank=True, max_length=80)),
                ("is_founder", models.BooleanField(default=False)),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="startups.startup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="startup_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TractionMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=20)),
                ("value_int", models.PositiveIntegerField(blank=True, null=True)),
                ("value_text", models.CharField(blank=True, max_length=300)),
                ("as_of_date", models.DateField()),
                ("visibility", models.CharField(default="private", max_length=10)),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traction",
                        to="startups.startup",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "-as_of_date", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="startup",
            index=models.Index(
                fields=["directory_opt_in", "country", "sector", "stage"],
                name="startup_directory_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="startup",
            index=models.Index(fields=["owner"], name="startup_owner_idx"),
        ),
        migrations.AddConstraint(
            model_name="startup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("year_founded__isnull", True),
                    models.Q(("year_founded__gte", 1900), ("year_founded__lte", 2100)),
                    _connector="OR",
                ),
                name="startup_year_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="startup",
            constraint=models.CheckConstraint(
                condition=models.Q(("completeness_score__lte", 100)), name="startup_score_max_100"
            ),
        ),
        migrations.AddConstraint(
            model_name="startupmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("startup", "user"),
                name="startupmember_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="startupmember",
            constraint=models.UniqueConstraint(
                models.F("startup"),
                django.db.models.functions.text.Lower("invited_email"),
                condition=models.Q(("invited_email", ""), _negated=True),
                name="startupmember_unique_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="startupmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    models.Q(("invited_email", ""), _negated=True),
                    _connector="OR",
                ),
                name="startupmember_has_identity",
            ),
        ),
        migrations.AddIndex(
            model_name="tractionmetric",
            index=models.Index(
                fields=["startup", "kind", "as_of_date"], name="traction_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tractionmetric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        (
                            "users",
                            "revenue_range",
                            "funding_range",
                            "milestone",
                            "award",
                            "partner",
                        ),
                    )
                ),
                name="traction_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tractionmetric",
            constraint=models.CheckConstraint(
                condition=models.Q(("visibility__in", ["private", "members", "public"])),
                name="traction_visibility_valid",
            ),
        ),
    ]
