# Generated by Django 5.2.17 on 2026-10-09 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailtoken_consentrecord_refreshtokenfamily"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("removed", "Removed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
