# Generated by Django 5.2.17 on 2026-10-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="send_nonce",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
