# Generated by Django 5.2.17 on 2026-10-10 08:22

import apps.core.ids
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("startups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organisation", models.CharField(blank=True, max_length=120)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("title", models.CharField(max_length=140)),
                ("type", models.CharField(max_length=12)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("remote", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("description_text", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("compensation", models.CharField(blank=True, max_length=120)),
                ("apply_method", models.CharField(max_length=5)),
                ("apply_target", models.CharField(max_length=300)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("member", "Member"), ("admin", "Admin")],
                        default="member",
                        max_length=6,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_warned_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=500)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="startups.startup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filters", models.JSONField(default=dict)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("instant", "Instant"), ("daily", "Daily")], max_length=7
                    ),
                ),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("require_approval", models.BooleanField(default=True)),
                ("default_duration_days", models.PositiveSmallIntegerField(default=60)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="job_settings_single_row"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_duration_days__gte", 1), ("default_duration_days__lte", 365)
                        ),
                        name="job_settings_duration_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status", "expires_at"], name="job_status_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["type", "created_at"], name="job_type_created_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["poster", "-created_at"], name="job_poster_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(("status", "published")),
                fields=["-published_at", "-id"],
                name="job_published_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="job_search_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        ("full_time", "part_time", "contract", "internship", "volunteer", "other"),
                    )
                ),
                name="job_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("apply_method__in", ("url", "email"))),
                name="job_apply_method_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("pending", "published", "closed", "expired", "rejected", "removed"),
                    )
                ),
                name="job_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["member", "admin"])), name="job_source_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="jobalert",
            index=models.Index(fields=["frequency", "last_sent_at"], name="job_alert_due_idx"),
        ),
        migrations.AddIndex(
            model_name="savedjob",
            index=models.Index(fields=["user", "-created_at", "-id"], name="saved_job_list_idx"),
        ),
        migrations.AddConstraint(
            model_name="savedjob",
            constraint=models.UniqueConstraint(fields=("user", "job"), name="saved_job_unique"),
        ),
    ]
