# Generated by Django 5.2.17 on 2026-10-10 19:38

import apps.core.ids
import django.db.models.constraints
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("description_text", models.TextField()),
                ("instructor", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=60)),
                ("level", models.CharField(max_length=12)),
                ("cover_key", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("removed", "Removed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("access", models.CharField(default="free", max_length=4)),
                ("price_minor", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("open_to_visitors", models.BooleanField(default=False)),
                ("certificate_enabled", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("rating_total", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stars", models.PositiveSmallIntegerField()),
                ("feedback", models.CharField(blank=True, max_length=1000)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="learning.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("free", "Free"), ("purchase", "Purchase"), ("grant", "Grant")],
                        max_length=8,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to="learning.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("holder_name", models.CharField(max_length=160)),
                ("course_title", models.CharField(max_length=160)),
                ("issued_at", models.DateTimeField()),
                (
                    "enrolment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="learning.enrolment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=160)),
                ("position", models.PositiveSmallIntegerField()),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("video_provider", models.CharField(blank=True, max_length=10)),
                ("video_id", models.CharField(blank=True, max_length=20)),
                ("video_url", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField(blank=True)),
                ("resource_url", models.CharField(blank=True, max_length=300)),
                ("resource_name", models.CharField(blank=True, max_length=160)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning.course",
                    ),
                ),
            ],
            options={
                "ordering": ["module__position", "position"],
            },
        ),
        migrations.AddField(
            model_name="enrolment",
            name="last_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="learning.lesson",
            ),
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position_seconds", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrolment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="learning.enrolment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="learning.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="learning.course",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="learning.module",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status", "access"], name="course_status_access_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["-published_at", "-id"], name="course_published_idx"),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__in", ("beginner", "intermediate", "advanced"))),
                name="course_level_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("access__in", ("free", "paid"))), name="course_access_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "published", "removed"])),
                name="course_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("access", "free"),
                    models.Q(("currency__gt", ""), ("price_minor__isnull", False)),
                    _connector="OR",
                ),
                name="paid_course_has_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="courserating",
            constraint=models.UniqueConstraint(fields=("course", "user"), name="rating_unique"),
        ),
        migrations.AddConstraint(
            model_name="courserating",
            constraint=models.CheckConstraint(
                condition=models.Q(("stars__gte", 1), ("stars__lte", 5)), name="rating_range"
            ),
        ),
        migrations.AddIndex(
            model_name="enrolment",
            index=models.Index(fields=["user", "-started_at"], name="enrolment_user_idx"),
        ),
        migrations.AddIndex(
            model_name="enrolment",
            index=models.Index(fields=["course", "completed_at"], name="enrolment_course_idx"),
        ),
        migrations.AddConstraint(
            model_name="enrolment",
            constraint=models.UniqueConstraint(fields=("course", "user"), name="enrolment_unique"),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.UniqueConstraint(
                fields=("enrolment", "lesson"), name="progress_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("course", "position"),
                name="module_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("module", "position"),
                name="lesson_position_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ("video", "reading", "resource"))),
                name="lesson_type_valid",
            ),
        ),
    ]
