# Generated by Django 5.2.17 on 2026-10-10 18:40

import apps.core.ids
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
                ("metric", models.CharField(max_length=80)),
                ("dimension", models.CharField(blank=True, max_length=80)),
                ("value", models.FloatField()),
            ],
            options={
                "indexes": [models.Index(fields=["metric", "day"], name="metric_series_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "metric", "dimension"), name="metric_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("refreshed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="dashboard_state_one"
                    )
                ],
            },
        ),
    ]
