# Generated by Django 5.2.17 on 2026-10-09 23:10

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("profile_photo", "Profile Photo"),
                            ("startup_logo", "Startup Logo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("discarded", "Discarded"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("declared_content_type", models.CharField(max_length=40)),
                ("declared_size", models.PositiveIntegerField()),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("quarantine_key", models.CharField(max_length=200, unique=True)),
                ("base_key", models.CharField(blank=True, max_length=200)),
                ("reject_reason", models.CharField(blank=True, max_length=40)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner", "created_at"], name="upload_owner_idx"),
                    models.Index(fields=["status", "expires_at"], name="upload_status_expiry_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "pending",
                                    "processing",
                                    "ready",
                                    "rejected",
                                    "expired",
                                    "discarded",
                                ],
                            )
                        ),
                        name="upload_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("purpose__in", ["profile_photo", "startup_logo"])),
                        name="upload_purpose_valid",
                    ),
                ],
            },
        ),
    ]
