# Generated by Django 5.2.17 on 2026-10-10 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_remove_upload_upload_purpose_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="upload",
            name="upload_purpose_valid",
        ),
        migrations.AlterField(
            model_name="upload",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("profile_photo", "Profile Photo"),
                    ("startup_logo", "Startup Logo"),
                    ("post_image", "Post Image"),
                    ("editorial_cover", "Editorial Cover"),
                    ("campaign_image", "Campaign Image"),
                    ("course_cover", "Course Cover"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="upload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "purpose__in",
                        [
                            "profile_photo",
                            "startup_logo",
                            "post_image",
                            "editorial_cover",
                            "campaign_image",
                            "course_cover",
                        ],
                    )
                ),
                name="upload_purpose_valid",
            ),
        ),
    ]
