# Generated by Django 5.2.17 on 2026-10-10 00:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0002_seed_reference_data"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="reference_sector_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="reference_skill_name_ci_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="reference_stage_name_ci_unique"
            ),
        ),
    ]
