# Generated by Django 5.2.17 on 2026-10-09 20:19

import apps.core.ids
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.serializers.json
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.CreateModel(
            name="PublicFounder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("full_name", models.CharField(max_length=120)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("skill_slugs", models.JSONField(default=list)),
                ("startup_slugs", models.JSONField(default=list)),
                ("newest_key", models.BigIntegerField()),
                ("name_key", models.CharField(max_length=120)),
                ("headline", models.CharField(blank=True, max_length=160)),
                ("bio", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("skill_names", models.TextField(blank=True)),
                ("startup_names", models.TextField(blank=True)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "card",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("source_updated_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="pubfounder_search_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper("full_name"), name="gin_trgm_ops"
                        ),
                        name="pubfounder_name_trgm_idx",
                    ),
                    models.Index(fields=["newest_key", "id"], name="pubfounder_newest_idx"),
                    models.Index(fields=["name_key", "id"], name="pubfounder_name_idx"),
                    models.Index(fields=["country"], name="pubfounder_country_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicStartup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("startup_id", models.UUIDField(unique=True)),
                ("owner_id", models.UUIDField()),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=2)),
                ("sector_slug", models.CharField(max_length=80)),
                ("stage_slug", models.CharField(max_length=80)),
                ("skill_slugs", models.JSONField(default=list)),
                ("featured_rank", models.PositiveSmallIntegerField(default=1)),
                ("newest_key", models.BigIntegerField()),
                ("name_key", models.CharField(max_length=120)),
                ("pitch", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("sector_name", models.CharField(blank=True, max_length=80)),
                ("founder_names", models.TextField(blank=True)),
                ("skill_names", models.TextField(blank=True)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "card",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("source_updated_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="pubstartup_search_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"
                        ),
                        name="pubstartup_name_trgm_idx",
                    ),
                    models.Index(
                        fields=["featured_rank", "newest_key", "id"], name="pubstartup_newest_idx"
                    ),
                    models.Index(
                        fields=["featured_rank", "name_key", "id"], name="pubstartup_name_idx"
                    ),
                    models.Index(fields=["country"], name="pubstartup_country_idx"),
                    models.Index(fields=["sector_slug"], name="pubstartup_sector_idx"),
                    models.Index(fields=["stage_slug"], name="pubstartup_stage_idx"),
                    models.Index(fields=["owner_id"], name="pubstartup_owner_idx"),
                ],
            },
        ),
    ]
