# Generated by Django 5.2.17 on 2026-10-10 00:35

import apps.core.ids
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

CREATE_TABLE = """
CREATE SEQUENCE analytics_event_seq;

CREATE TABLE analytics_event (
    id uuid NOT NULL,
    seq bigint NOT NULL,
    name varchar(60) NOT NULL,
    actor_id uuid,
    anonymous_id uuid,
    properties jsonb NOT NULL DEFAULT '{}',
    source varchar(10) NOT NULL,
    occurred_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL,
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);

-- Last resort: an event outside any prepared month lands here instead of failing a request.
CREATE TABLE analytics_event_default PARTITION OF analytics_event DEFAULT;

-- Time ranges in an append-only table: BRIN is tiny and fast to maintain.
CREATE INDEX analytics_event_time_brin ON analytics_event USING brin (occurred_at);
CREATE INDEX analytics_event_seq_idx ON analytics_event (seq);
CREATE INDEX analytics_event_name_idx ON analytics_event (name, occurred_at);
CREATE INDEX analytics_event_actor_idx ON analytics_event (actor_id, occurred_at)
    WHERE actor_id IS NOT NULL;
CREATE INDEX analytics_event_anon_idx ON analytics_event (anonymous_id, occurred_at)
    WHERE anonymous_id IS NOT NULL;
"""

DROP_TABLE = """
DROP TABLE analytics_event;
DROP SEQUENCE analytics_event_seq;
"""


def create_initial_partitions(apps, schema_editor):
    from django.utils import timezone

    from apps.analytics.partitions import ensure_month_partitions

    ensure_month_partitions(timezone.now().date(), months_ahead=3)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(CREATE_TABLE, DROP_TABLE),
        migrations.RunPython(create_initial_partitions, migrations.RunPython.noop),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.BigIntegerField()),
                ("name", models.CharField(max_length=60)),
                ("actor_id", models.UUIDField(null=True)),
                ("anonymous_id", models.UUIDField(null=True)),
                (
                    "properties",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("source", models.CharField(max_length=10)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
            ],
            options={
                "db_table": "analytics_event",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ForwardCursor",
            fields=[
                ("name", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("last_seq", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opted_out", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdentityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anonymous_id", models.UUIDField(unique=True)),
                ("forwarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["forwarded_at"], name="identity_pending_idx")],
            },
        ),
    ]
