# Generated by Django 5.2.17 on 2026-10-11 00:26

import apps.core.ids
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expertise", models.JSONField(default=list)),
                ("years_experience", models.PositiveSmallIntegerField()),
                ("current_role", models.CharField(max_length=120)),
                ("company", models.CharField(max_length=120)),
                ("linkedin_url", models.CharField(max_length=300)),
                ("industries", models.JSONField(default=list)),
                ("stages", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                ("timezone", models.CharField(max_length=64)),
                ("weekly_hours", models.PositiveSmallIntegerField()),
                ("availability_note", models.CharField(blank=True, max_length=500)),
                ("motivation", models.TextField()),
                ("conduct_accepted_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("info_requested", "Info Requested"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=14,
                    ),
                ),
                ("decision_reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("about", models.CharField(blank=True, max_length=1000)),
                ("expertise", models.JSONField(default=list)),
                ("years_experience", models.PositiveSmallIntegerField()),
                ("current_role", models.CharField(max_length=120)),
                ("company", models.CharField(max_length=120)),
                ("industries", models.JSONField(default=list)),
                ("stages", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                ("timezone", models.CharField(max_length=64)),
                ("capacity_per_week", models.PositiveSmallIntegerField(default=3)),
                ("paused", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("approved_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("rating_total", models.PositiveIntegerField(default=0)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mentorship.mentorapplication",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="mentorapplication",
            index=models.Index(
                fields=["status", "created_at"], name="mentorapp_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("pending", "info_requested", "approved", "declined", "withdrawn"),
                    )
                ),
                name="mentorapp_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("pending", "info_requested"))),
                fields=("applicant",),
                name="mentorapp_one_open_per_applicant",
            ),
        ),
        migrations.AddIndex(
            model_name="mentorprofile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["expertise"], name="mentorprofile_expertise_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorprofile",
            index=models.Index(fields=["status", "paused"], name="mentorprofile_listing_idx"),
        ),
        migrations.AddConstraint(
            model_name="mentorprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "revoked"])),
                name="mentorprofile_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity_per_week__gte", 1), ("capacity_per_week__lte", 20)),
                name="mentorprofile_capacity_range",
            ),
        ),
    ]
