# Generated by Django 5.2.17 on 2026-10-11 01:25

from django.contrib.postgres.operations import BtreeGistExtension
import apps.core.ids
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0002_mentor_interest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("one_off", "One Off")], max_length=8
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("start_minute", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_minute", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "week_span",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_span",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeekerNeeds",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("needs", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="session_minutes",
            field=models.PositiveSmallIntegerField(default=45),
        ),
        migrations.AddConstraint(
            model_name="mentorprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("session_minutes__in", [30, 45, 60])),
                name="mentorprofile_session_minutes_valid",
            ),
        ),
        migrations.AddField(
            model_name="availabilityslot",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seekerneeds",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentoring_needs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityslot",
            index=models.Index(fields=["mentor", "kind"], name="availabilityslot_mentor_idx"),
        ),
        migrations.AddConstraint(
            model_name="availabilityslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "weekly"),
                        ("weekday__gte", 0),
                        ("weekday__lte", 6),
                        ("end_minute__lte", 1440),
                        ("start_minute__gte", 0),
                        ("end_minute__gt", models.F("start_minute")),
                        ("week_span__isnull", False),
                        ("ends_at__isnull", True),
                        ("starts_at__isnull", True),
                        ("time_span__isnull", True),
                    ),
                    models.Q(
                        ("kind", "one_off"),
                        ("ends_at__isnull", False),
                        ("starts_at__isnull", False),
                        ("time_span__isnull", False),
                        ("ends_at__gt", models.F("starts_at")),
                        ("week_span__isnull", True),
                        ("weekday__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="availabilityslot_shape_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityslot",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("kind", "weekly")),
                expressions=[("mentor", "="), ("week_span", "&&")],
                name="availabilityslot_weekly_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityslot",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("kind", "one_off")),
                expressions=[("mentor", "="), ("time_span", "&&")],
                name="availabilityslot_one_off_no_overlap",
            ),
        ),
    ]
