# Generated by Django 5.2.17 on 2026-10-10 06:56

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("startups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(max_length=12)),
                ("body", models.TextField()),
                ("body_text", models.TextField()),
                ("country", models.CharField(blank=True, max_length=2)),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                ("featured_at", models.DateTimeField(blank=True, null=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("reaction_count", models.PositiveIntegerField(default=0)),
                ("reaction_counts", models.JSONField(blank=True, default=dict)),
                ("engagement", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="startups.startup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("body", models.TextField()),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("reaction_count", models.PositiveIntegerField(default=0)),
                ("reaction_counts", models.JSONField(blank=True, default=dict)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="feed.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="feed.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_key", models.CharField(max_length=200)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="feed.post",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("post", "Post"), ("comment", "Comment")], max_length=8
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("kind", models.CharField(max_length=12)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-created_at", "-id"], name="feed_post_newest_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-engagement", "-created_at", "-id"], name="feed_post_hot_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["category", "-created_at"], name="feed_post_category_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author", "-created_at"], name="feed_post_author_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["country", "-created_at"], name="feed_post_country_idx"),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        ("update", "question", "win", "resource", "event", "opportunity"),
                    )
                ),
                name="feed_post_category_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post", "created_at", "id"], name="feed_comment_post_idx"),
        ),
        migrations.AddConstraint(
            model_name="postimage",
            constraint=models.UniqueConstraint(
                fields=("post", "position"), name="feed_image_position_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(fields=["user", "target_type", "target_id"], name="feed_mine_idx"),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("target_type", "target_id", "user", "kind"), name="feed_reaction_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("like", "celebrate", "insightful"))),
                name="feed_reaction_kind_valid",
            ),
        ),
    ]
