# Generated by Django 5.2.17 on 2026-10-10 07:10

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "followee_type",
                    models.CharField(
                        choices=[("member", "Member"), ("startup", "Startup")], max_length=8
                    ),
                ),
                ("followee_id", models.UUIDField()),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["follower", "-created_at", "-id"], name="feed_follow_mine_idx"
                    ),
                    models.Index(
                        fields=["followee_type", "followee_id"], name="feed_follow_target_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "followee_type", "followee_id"),
                        name="feed_follow_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("followee_type__in", ["member", "startup"])),
                        name="feed_follow_type_valid",
                    ),
                ],
            },
        ),
    ]
