# Generated by Django 5.2.17 on 2026-10-10 07:24

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_follow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("post", "Post"), ("comment", "Comment")], max_length=8
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("reason", models.CharField(max_length=14)),
                ("details", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("actioned", "Actioned"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="feed_report_queue_idx"),
                    models.Index(
                        fields=["target_type", "target_id"], name="feed_report_target_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reporter", "target_type", "target_id"), name="feed_report_once"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "reason__in",
                                (
                                    "spam",
                                    "harassment",
                                    "misinformation",
                                    "illegal",
                                    "inappropriate",
                                    "other",
                                ),
                            )
                        ),
                        name="feed_report_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["open", "reviewed", "actioned"])),
                        name="feed_report_status",
                    ),
                ],
            },
        ),
    ]
