# Generated by Django 5.2.17 on 2026-10-10 07:46

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url_hash", models.CharField(max_length=64, unique=True)),
                ("url", models.CharField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready"), ("failed", "Failed")],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("site_name", models.CharField(blank=True, max_length=100)),
                ("image_key", models.CharField(blank=True, max_length=200)),
                ("fail_code", models.CharField(blank=True, max_length=30)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="feed.post",
                    ),
                ),
                (
                    "preview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="feed.linkpreview",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(fields=("post", "position"), name="feed_link_position"),
                    models.UniqueConstraint(fields=("post", "preview"), name="feed_link_once"),
                ],
            },
        ),
    ]
