# Generated by Django 5.2.17 on 2026-10-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_linkpreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mentioned",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
