# Generated by Django 5.2.17 on 2026-10-09 23:51

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suppression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_hash", models.CharField(max_length=64, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=20)),
                ("event_id", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["processed_at", "created_at"], name="webhook_pending_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="webhook_delivery_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=20)),
                ("provider_message_id", models.CharField(max_length=100)),
                ("email_hash", models.CharField(max_length=64)),
                ("occurred_at", models.CharField(blank=True, max_length=40)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="notifications.webhookdelivery",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider_message_id"], name="delivery_event_message_idx"),
                    models.Index(fields=["email_hash", "kind"], name="delivery_event_email_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("delivery", "kind", "provider_message_id", "email_hash"),
                        name="delivery_event_unique",
                    )
                ],
            },
        ),
    ]
